---
- name: "Apply new configuration for HAProxy"
  systemd:
    name: haproxy
    state: restarted

- name: "Apply new configuration for Keepalived"
  systemd:
    name: keepalived
    state: restarted
